using System;

// Token: 0x0200006A RID: 106
public class Ending_EV
{
	// Token: 0x040002B7 RID: 695
	public const int MAX_NUMBER_OF_PORTRAITS_FOR_LINEAGE = 20;

	// Token: 0x040002B8 RID: 696
	public const float ENDING_COUNTDOWN_TIMER = 10f;

	// Token: 0x040002B9 RID: 697
	public static readonly string[] GARDEN_PREFIGHT_DIALOGUE_LOCIDS = new string[]
	{
		"LOC_ID_J_GARDEN_EXPLAINING_EVERYTHING_1",
		"LOC_ID_J_GARDEN_KNOWLEDGE_OF_THE_LOOP_1",
		"LOC_ID_J_GARDEN_HESTIA_IN_DETAIL_1",
		"LOC_ID_J_GARDEN_MISTAKES_HE_MADE_1",
		"LOC_ID_J_GARDEN_MUSINGS_OF_CHARON_1",
		"LOC_ID_J_GARDEN_SON_OF_LAMECH_1",
		"LOC_ID_J_GARDEN_OFF_ON_TRAVEL_1",
		"LOC_ID_J_GARDEN_DISCOVERS_PLAN_1",
		"LOC_ID_J_GARDEN_REPEATING_FIGHT_1"
	};

	// Token: 0x040002BA RID: 698
	public static readonly string[] GARDEN_PREFIGHT_REPEAT_DIALOGUE_LOCIDS = new string[]
	{
		"LOC_ID_J_GARDEN_REPEAT_FIGHT_1",
		"LOC_ID_J_GARDEN_REPEAT_FIGHT_2",
		"LOC_ID_J_GARDEN_REPEAT_FIGHT_3",
		"LOC_ID_J_GARDEN_REPEAT_FIGHT_4",
		"LOC_ID_J_GARDEN_REPEAT_FIGHT_5",
		"LOC_ID_J_GARDEN_REPEAT_FIGHT_6"
	};

	// Token: 0x040002BB RID: 699
	public static readonly string[] GARDEN_POSTFIGHT_DIALOGUE_LOCIDS = new string[]
	{
		"LOC_ID_J_GARDEN_BEATEN_BY_PLAYER_1",
		"LOC_ID_J_GARDEN_BEATEN_BY_PLAYER_2",
		"LOC_ID_J_GARDEN_BEATEN_BY_PLAYER_3",
		"LOC_ID_J_GARDEN_BEATEN_BY_PLAYER_4",
		"LOC_ID_J_GARDEN_BEATEN_BY_PLAYER_5",
		"LOC_ID_J_GARDEN_SPECIAL_BEATEN_GIVE_KEY_1"
	};

	// Token: 0x040002BC RID: 700
	public static readonly string[] GARDEN_POSTFIGHT_REPEAT_DIALOGUE_LOCIDS = new string[]
	{
		"LOC_ID_J_GARDEN_BEATEN_IDLE_TALK_1",
		"LOC_ID_J_GARDEN_BEATEN_IDLE_TALK_2",
		"LOC_ID_J_GARDEN_BEATEN_IDLE_TALK_3",
		"LOC_ID_J_GARDEN_BEATEN_IDLE_TALK_4",
		"LOC_ID_J_GARDEN_BEATEN_IDLE_TALK_5"
	};

	// Token: 0x040002BD RID: 701
	public const int MIN_DEATHS_BEFORE_HESTIA_CUTSCENE = 6;

	// Token: 0x040002BE RID: 702
	public const float HESTIA_CUTSCENE_CHANCE_PER_DEATH = 0.25f;

	// Token: 0x040002BF RID: 703
	public const float DEATH_DEFY_TRANSITION_DELAY = 1f;

	// Token: 0x040002C0 RID: 704
	public static readonly string[] TREE_CUTSCENE_DIALOGUE_1_LOCID = new string[]
	{
		"LOC_ID_TREE_BIG_TEXT_YOUR_DUTY_1",
		"LOC_ID_TREE_BIG_TEXT_MANY_YEARS_1",
		"LOC_ID_TREE_BIG_TEXT_NO_GROWTH_1",
		"LOC_ID_TREE_BIG_TEXT_CHANGE_1",
		"LOC_ID_TREE_BIG_TEXT_WATER_RISES_1",
		"LOC_ID_TREE_BIG_TEXT_WHITE_TREE_1"
	};

	// Token: 0x040002C1 RID: 705
	public static readonly string[] TREE_CUTSCENE_DIALOGUE_2_LOCID = new string[]
	{
		"LOC_ID_TREE_BIG_TEXT_YOUR_DUTY_2",
		"LOC_ID_TREE_BIG_TEXT_MANY_YEARS_2",
		"LOC_ID_TREE_BIG_TEXT_NO_GROWTH_2",
		"LOC_ID_TREE_BIG_TEXT_CHANGE_2",
		"LOC_ID_TREE_BIG_TEXT_WATER_RISES_2",
		"LOC_ID_TREE_BIG_TEXT_WHITE_TREE_2"
	};

	// Token: 0x040002C2 RID: 706
	public static readonly string[] HESTIA_CUTSCENE_DIALOGUE_1_LOCID = new string[]
	{
		"LOC_ID_HESTIA_BIG_TEXT_NEW_CONTRACT_1",
		"LOC_ID_HESTIA_BIG_TEXT_FAMILY_RELIQUARY_1",
		"LOC_ID_HESTIA_BIG_TEXT_BELL_RINGS_1",
		"LOC_ID_HESTIA_BIG_TEXT_MADE_FROM_SEED_1",
		"LOC_ID_HESTIA_BIG_TEXT_MEMORIES_SHALL_PASS_1",
		"LOC_ID_HESTIA_BIG_TEXT_CONTRACT_1",
		"LOC_ID_HESTIA_BIG_TEXT_BODY_TRANSPORT_1",
		"LOC_ID_HESTIA_BIG_TEXT_LEGACY_1"
	};

	// Token: 0x040002C3 RID: 707
	public static readonly string[] HESTIA_CUTSCENE_DIALOGUE_2_LOCID = new string[]
	{
		"LOC_ID_HESTIA_BIG_TEXT_NEW_CONTRACT_2",
		"LOC_ID_HESTIA_BIG_TEXT_FAMILY_RELIQUARY_2",
		"LOC_ID_HESTIA_BIG_TEXT_BELL_RINGS_2",
		"LOC_ID_HESTIA_BIG_TEXT_MADE_FROM_SEED_2",
		"LOC_ID_HESTIA_BIG_TEXT_MEMORIES_SHALL_PASS_2",
		"LOC_ID_HESTIA_BIG_TEXT_CONTRACT_2",
		"LOC_ID_HESTIA_BIG_TEXT_BODY_TRANSPORT_2",
		"LOC_ID_HESTIA_BIG_TEXT_LEGACY_2"
	};
}
